language: ruby
rvm:
- 2.3.5

deploy:
  provider: heroku
  api_key:
    secure: px3jkCkU8xhXDmYW8J/hMmCvccCyXRm/2ux/UvCk1c9E6GjiHZtTM6aOIj6rDzRMb51+I20y21qLrznszdRCVh8Bvuxoy7RBHmya5XTOr/vAIw/DOwsjkbu2uv54DMYDNe2+OKJ75CtU/PwK2nCVtiEDAbti1JCH/TCl0o/2zGj/9BJy/XqrN3rbfCeIoQ+4OqGcwvPT1zVv4JbBZrkCMiGBJbcHUDY3v8eGRyzVYIQSQ6ptr42/noWYP4soQ9pL9tTxUUAlZYc0Pe/YKxrkbQL58izgXp1JrjwjKHJPg3gptbpoxgIG4yuUQrqjvv2eiDXMZDCEyRohMIDxEIDPFwH0pIt79oyxgX8x2jt97qCCD4U6cg8gQbnbgDLZBqRiA3thEcQr6xhsA7ICXM0gGIxus4S2EKTFVvjzybcBrGfYASCKPOrPVJpM4Hvs+Y48b49whTEs4lvdTAR4D5kf1ZFQ/TKwEMO8Ff33vU4l4IVBcnBpGXZSTyaWU3H3ArJ4em+xu/x8pbaDJMxzM1mI64WGVyYaNUeOJ9ug2Edp/nWN5BBNv1rL8guWTnOdSk1RsgUTxNgub5a0tweLFVDKSuAPRvLkktdKYjim81REc/aYlx4pNKFrNhoqn7CfP0ZVZzTsm17yIGR2hSEHMZlIYy5Yt0tgXG/ciYLOdhtFvYU=
  app: projet-harbane