language: ruby
rvm:
- 2.3.5
deploy:
  provider: heroku
  api_key:
    secure: plx3Uqxo2jiiIGd6uVm6noKmoXVLGZW+8s6TL9oUGZGra+zRjlC/u23qWr5A9OnW3lPFCBrblJ9SMFivl4+ihAmrB2mXN1NBFR8CFu79zZYzwqYDiSjzb+Tj5IsmJPKPGGBpC3R3yk+2ukSN5oYu59ecWLxAt7uNG2ftjb4ZjOvCN73Ghv7eG9LSjXUlGvHCbGPfkm8dgfDT/2eNGZ9W5gFLBX8XEfVHCFAKTYkTETpaaJC3HlpZNVe3y79/UCEw90UqAmiZEgnBtn3yur5wv4TKUnOtcshZWtYyfRSX/BCazKVue8LZVy7DNM2at6F0uQiGnc/ENh/EJoVGVVVC0axXS5dXwVKEpSeCeXUiccPDjOSagp+LrKH2wgV+JETBGf1b3WA2aCJSLcAsG0rdfT0nYYAGUUzQYqMeS86NX1aWz78XGmOJ9g0QJzlGaYydjBgt7uoeQWVb4sZyIDb2QIO+pp5fb39bKyDB5svuux2vwmRCFzRr/eBN2hASfuUG/iS/KIbqrRQSclb8//zAO88jSX1ePHf7U4A6V0iFOsHriOw1wHt0GGd9rmYeYyhmBvboT6XH02jVyptyoqeQ2Sijdn6KLEg8u3A5fHlkTRnnVhGMdf6/z2Kic4PDSzces9yDNDgwytqIDdh7+cKV3L3D0Jg69aEyiF0M3gSVF0I=
  app: projet-harbane
  run: "rake db:migrate"
